{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-app.fullname" . }}-secret
  labels:
    {{- include "weather-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  openweather-api-key: {{ .Values.secrets.openweatherApiKey | quote }}
{{- end }}
