apiVersion: v1
kind: Secret
metadata:
  name: weather-app-secret
type: Opaque
stringData:
  # Cette valeur sera remplacée par overlay
  # Pour prod et preprod, utilisez des secrets externes (Sealed Secrets, External Secrets, etc.)
  OPENWEATHER_API_KEY: "demo"
