apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-prod

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

configMapGenerator:
  - name: weather-app-config
    behavior: merge
    literals:
      - ENVIRONMENT=production

patches:
  - path: deployment-patch.yaml

commonLabels:
  environment: production

images:
  - name: weather-app
    newName: your-registry/weather-app
    newTag: latest
