apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-preprod

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: weather-app-config
    behavior: merge
    literals:
      - ENVIRONMENT=preprod

patches:
  - path: deployment-patch.yaml

commonLabels:
  environment: preprod

images:
  - name: weather-app
    newName: your-registry/weather-app
    newTag: preprod
